import Head from 'next/head';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import { getCookie } from '../../../services/cookies';
import { GetServerSidePropsContext } from 'next';
import Permission from '../../../components/Admin/Permission/Permission';
import { AccountApi } from '../../../services/api/account';
import { useEffect, useState } from 'react';
import { PermissionPrams } from '../../../services/types';
import CreateGroupAdmin from '../../../components/Admin/Group/CreateGroup';

export default function CreateGroup() {
  return (
    <>
      <Head>
        <title>Create Group</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <CreateGroupAdmin update={false} />
      </Layout>
    </>
  );
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const token = await getCookie('token', ctx);
  if (token) {
    try {
      console.log('server');
      //   console.log('token server: ', token);
      AccountApi.logout(token)
        .then((res) => {
          console.log(res);
        })
        .catch((e) => {
          console.log('*' + token + '*');
        });
      return {
        props: {
          //   permissionsList: res,
        },
      };
    } catch (e) {
      console.log('server error: ', e);
    }

    return {
      props: {},
    };
  } else {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
}
