import Head from 'next/head';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import { getCookie } from '../../../services/cookies';
import { GetServerSidePropsContext } from 'next';
import CreateGroupAdmin from '../../../components/Admin/Group/CreateGroup';

export default function ViewGroupPage() {
  return (
    <>
      <Head>
        <title>Update Group</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout>
        <CreateGroupAdmin update />
      </Layout>
    </>
  );
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const token = await getCookie('token', ctx);
  if (token) {
    try {
    } catch (e) {
      console.log('server error: ', e);
    }

    return {
      props: {},
    };
  } else {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
}
