import { Box } from '@mui/material';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import React from 'react';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import UpdateProduct from '../../../components/Admin/Products/UpdateProduct/UpdateProduct';
import { ProductApi } from '../../../services/api/product';
import { getCookie } from '../../../services/cookies';

interface IProductInfo {
  data: any;
}

const ProductInfo = (data: IProductInfo) => {
  return (
    <>
      <Head>
        <title>Product Details</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <UpdateProduct data={data.data} />
      </Layout>
    </>
  );
};

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const token = await getCookie('token', ctx);
  const { productId } = ctx.query;
  console.log('productId: ', productId);
  if (token) {
    try {
      const [res] = await Promise.all([
        ProductApi.getProductById(productId as string, token),
      ]);
      return {
        props: {
          ...res,
        },
      };
    } catch (e) {}

    return {
      props: {},
    };
  } else {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
}

export default ProductInfo;
