import Head from 'next/head';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import { ProductApi } from '../../../services/api/product';
import { getCookie } from '../../../services/cookies';
import { GetServerSidePropsContext } from 'next';
import UpdateProduct from '../../../components/Admin/Products/UpdateProduct/UpdateProduct';

export default function AddProduct({ categoryList }: any) {
  return (
    <>
      <Head>
        <title>Add Product | Linen A</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <UpdateProduct categoryList={categoryList} />
      </Layout>
    </>
  );
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const token = await getCookie('token', ctx);

  if (token) {
    try {
      const [res] = await Promise.all([ProductApi.categoryList(token)]);
      return {
        props: {
          categoryList: res.data.data,
        },
      };
    } catch (e) {}

    return {
      props: {},
    };
  } else {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
}
