import Head from 'next/head';
import React from 'react';
import { Box } from '@mui/material';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import ListDetailProduct from '../../../components/Admin/Products/Products';
import { AccountApi } from '../../../services/api/account';
import { PagesApi } from '../../../services/api/pages';
import { getCookie } from '../../../services/cookies';

interface IProduct {
  // roles: any;
}

const Product = (props: any) => {
  console.log('data: ', props);
  return (
    <>
      <Head>
        <title>Product</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Box>
          <ListDetailProduct rows={props.props.data.data} />
        </Box>
      </Layout>
    </>
  );
};

Product.getInitialProps = async () => {
  const token = getCookie('token');
  const [res, data] = await Promise.all([
    AccountApi.roleAdmin(token as string | undefined),
    PagesApi.adminProduct(1, token as string),
  ]);
  return {
    props: {
      ...res,
      ...data,
    },
  };

  // const res = await AccountApi.roleAdmin(token as string | undefined);
  // return { ...res };

  // Fetch data from external API
  // const token = localStorage.getItem('token');
  // const res = await AccountApi.roleAdmin(token as string | undefined);
  // console.log('res: ', res);
  // // Pass data to the page via props
  // return { ...res };
};

export default Product;
