import Head from 'next/head';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import ViewPermissions from '../../../components/Admin/Permission/View/ViewPermission';

export default function ViewPermission() {
  return (
    <>
      <Head>
        <title>View Permissions</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ViewPermissions />
      </Layout>
    </>
  );
}
