import Head from 'next/head';
import React from 'react';
import Layout from '../../../components/Admin/LayoutAdmin/LayoutAdmin';
import UpdateProvince from '../../../components/Admin/Province/UpdateProvince';

type Props = {};

const CreateProvince = (props: Props) => {
  return (
    <>
      <Head>
        <title>Create Province | Linen A</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <UpdateProvince />
      </Layout>
    </>
  );
};

export default CreateProvince;
